@baseUrl = http://localhost:3333

# @name authentication
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "johndoe6@gmail.com",
  "password": "123456789"
}

###

# @name Registration
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
	"name": "JohnDoe",
  "email": "johndoe6@gmail.com",
  "password": "12345678"
}


