@baseUrl = http://localhost:3333

# @name authentication
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "johndoe5@gmail.com",
  "password": "1234568"
}

###

# @name Registration
POST {{baseUrl}}/register
Content-Type: application/json

{
	"name": "JohnDoe",
  "email": "johndoe5@gmail.com",
  "password": "1234568"
}


