version: '3.8'

services:
  postgres:
    container_name: learnix-database-api
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: learnix
      POSTGRES_PASSWORD: learnix
      POSTGRES_DB: learnix_db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
